// Auto-generated by LibreLane
module serial2parallel(
`ifdef USE_POWER_PINS
  input VDD,
  input VSS,
`endif
  input clk,
  input shift_in,
  input data_in,
  input done_in,
  input reset,
  output[11:0] dout
);
endmodule
