/* Generated by Yosys 0.66 (git sha1 86f2ddebce7e98ce7cacc27e8a5c14cb53b51b51, clang++ 21.1.8 -fPIC -O3) */

module sg13g2_a21o_1(X, A1, A2, B1);
  output X;
  wire X;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
endmodule

module sg13g2_a21o_2(X, A1, A2, B1);
  output X;
  wire X;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
endmodule

module sg13g2_a21oi_1(Y, A1, A2, B1);
  output Y;
  wire Y;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
endmodule

module sg13g2_a21oi_2(Y, A1, A2, B1);
  output Y;
  wire Y;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
endmodule

module sg13g2_a221oi_1(Y, A1, A2, B1, B2, C1);
  output Y;
  wire Y;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
endmodule

module sg13g2_a22oi_1(Y, A1, A2, B1, B2);
  output Y;
  wire Y;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
endmodule

module sg13g2_and2_1(X, A, B);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_and2_2(X, A, B);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_and3_1(X, A, B, C);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_and3_2(X, A, B, C);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_and4_1(X, A, B, C, D);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_and4_2(X, A, B, C, D);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_antennanp(A);
  input A;
  wire A;
endmodule

module sg13g2_buf_1(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_buf_16(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_buf_2(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_buf_4(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_buf_8(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_decap_4();
endmodule

module sg13g2_decap_8();
endmodule

module sg13g2_dfrbp_1(Q, Q_N, CLK, D, RESET_B);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dfrbp_2(Q, Q_N, CLK, D, RESET_B);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dfrbpq_1(Q, CLK, D, RESET_B);
  output Q;
  wire Q;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dfrbpq_2(Q, CLK, D, RESET_B);
  output Q;
  wire Q;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dlhq_1(Q, D, GATE);
  output Q;
  wire Q;
  input D;
  wire D;
  input GATE;
  wire GATE;
endmodule

module sg13g2_dlhr_1(Q, Q_N, D, GATE, RESET_B);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input D;
  wire D;
  input GATE;
  wire GATE;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dlhrq_1(Q, D, GATE, RESET_B);
  output Q;
  wire Q;
  input D;
  wire D;
  input GATE;
  wire GATE;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dllr_1(Q, Q_N, D, GATE_N, RESET_B);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dllrq_1(Q, D, GATE_N, RESET_B);
  output Q;
  wire Q;
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sg13g2_dlygate4sd1_1(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_dlygate4sd2_1(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_dlygate4sd3_1(X, A);
  output X;
  wire X;
  input A;
  wire A;
endmodule

module sg13g2_ebufn_2(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_ebufn_4(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_ebufn_8(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_einvn_2(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_einvn_4(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_einvn_8(Z, A, TE_B);
  output Z;
  wire Z;
  input A;
  wire A;
  input TE_B;
  wire TE_B;
endmodule

module sg13g2_fill_1();
endmodule

module sg13g2_fill_2();
endmodule

module sg13g2_fill_4();
endmodule

module sg13g2_fill_8();
endmodule

module sg13g2_inv_1(Y, A);
  output Y;
  wire Y;
  input A;
  wire A;
endmodule

module sg13g2_inv_16(Y, A);
  output Y;
  wire Y;
  input A;
  wire A;
endmodule

module sg13g2_inv_2(Y, A);
  output Y;
  wire Y;
  input A;
  wire A;
endmodule

module sg13g2_inv_4(Y, A);
  output Y;
  wire Y;
  input A;
  wire A;
endmodule

module sg13g2_inv_8(Y, A);
  output Y;
  wire Y;
  input A;
  wire A;
endmodule

module sg13g2_lgcp_1(GCLK, CLK, GATE);
  output GCLK;
  wire GCLK;
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
endmodule

module sg13g2_mux2_1(X, A0, A1, S);
  output X;
  wire X;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
endmodule

module sg13g2_mux2_2(X, A0, A1, S);
  output X;
  wire X;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
endmodule

module sg13g2_mux4_1(X, A0, A1, A2, A3, S0, S1);
  output X;
  wire X;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input S0;
  wire S0;
  input S1;
  wire S1;
endmodule

module sg13g2_nand2_1(Y, A, B);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_nand2_2(Y, A, B);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_nand2b_1(Y, A_N, B);
  output Y;
  wire Y;
  input A_N;
  wire A_N;
  input B;
  wire B;
endmodule

module sg13g2_nand2b_2(Y, A_N, B);
  output Y;
  wire Y;
  input A_N;
  wire A_N;
  input B;
  wire B;
endmodule

module sg13g2_nand3_1(Y, A, B, C);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_nand3b_1(Y, A_N, B, C);
  output Y;
  wire Y;
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_nand4_1(Y, A, B, C, D);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_nor2_1(Y, A, B);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_nor2_2(Y, A, B);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_nor2b_1(Y, A, B_N);
  output Y;
  wire Y;
  input A;
  wire A;
  input B_N;
  wire B_N;
endmodule

module sg13g2_nor2b_2(Y, A, B_N);
  output Y;
  wire Y;
  input A;
  wire A;
  input B_N;
  wire B_N;
endmodule

module sg13g2_nor3_1(Y, A, B, C);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_nor3_2(Y, A, B, C);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_nor4_1(Y, A, B, C, D);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_nor4_2(Y, A, B, C, D);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_o21ai_1(Y, A1, A2, B1);
  output Y;
  wire Y;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
endmodule

module sg13g2_or2_1(X, A, B);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_or2_2(X, A, B);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_or3_1(X, A, B, C);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_or3_2(X, A, B, C);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
endmodule

module sg13g2_or4_1(X, A, B, C, D);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_or4_2(X, A, B, C, D);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
endmodule

module sg13g2_sdfbbp_1(Q, Q_N, CLK, D, RESET_B, SCD, SCE, SET_B);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sg13g2_sdfrbp_1(Q, Q_N, CLK, D, RESET_B, SCD, SCE);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sg13g2_sdfrbp_2(Q, Q_N, CLK, D, RESET_B, SCD, SCE);
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sg13g2_sdfrbpq_1(Q, CLK, D, RESET_B, SCD, SCE);
  output Q;
  wire Q;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sg13g2_sdfrbpq_2(Q, CLK, D, RESET_B, SCD, SCE);
  output Q;
  wire Q;
  input CLK;
  wire CLK;
  input D;
  wire D;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sg13g2_sighold(SH);
  inout SH;
  wire SH;
endmodule

module sg13g2_slgcp_1(GCLK, GATE, CLK, SCE);
  output GCLK;
  wire GCLK;
  input GATE;
  wire GATE;
  input CLK;
  wire CLK;
  input SCE;
  wire SCE;
endmodule

module sg13g2_tiehi(L_HI);
  output L_HI;
  wire L_HI;
endmodule

module sg13g2_tielo(L_LO);
  output L_LO;
  wire L_LO;
endmodule

module sg13g2_xnor2_1(Y, A, B);
  output Y;
  wire Y;
  input A;
  wire A;
  input B;
  wire B;
endmodule

module sg13g2_xor2_1(X, A, B);
  output X;
  wire X;
  input A;
  wire A;
  input B;
  wire B;
endmodule
