/* Generated by Yosys 0.66 (git sha1 86f2ddebce7e98ce7cacc27e8a5c14cb53b51b51, clang++ 21.1.8 -fPIC -O3) */

module sg13g2_Corner(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler1000(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler10000(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler200(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler2000(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler400(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_Filler4000(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadAnalog(pad, padres, vdd, vss, iovdd, iovss);
  inout pad;
  wire pad;
  inout padres;
  wire padres;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadIOVdd(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadIOVss(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadIn(pad, p2c, vdd, vss, iovdd, iovss);
  input pad;
  wire pad;
  output p2c;
  wire p2c;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadInOut16mA(pad, c2p, p2c, c2p_en, vdd, vss, iovdd, iovss);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  output p2c;
  wire p2c;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadInOut30mA(pad, c2p, p2c, c2p_en, vdd, vss, iovdd, iovss);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  output p2c;
  wire p2c;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadInOut4mA(pad, c2p, p2c, c2p_en, vdd, vss, iovdd, iovss);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  output p2c;
  wire p2c;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadOut16mA(pad, c2p, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadOut30mA(pad, c2p, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadOut4mA(pad, c2p, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadTriOut16mA(pad, c2p, c2p_en, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadTriOut30mA(pad, c2p, c2p_en, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadTriOut4mA(pad, c2p, c2p_en, vdd, vss, iovdd, iovss);
  output pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadVdd(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule

module sg13g2_IOPadVss(vdd, vss, iovdd, iovss);
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  inout iovdd;
  wire iovdd;
  inout iovss;
  wire iovss;
endmodule
