/* Generated by Yosys 0.66 (git sha1 86f2ddebce7e98ce7cacc27e8a5c14cb53b51b51, clang++ 21.1.8 -fPIC -O3) */

module serial2parallel(clk, shift_in, data_in, done_in, reset, VDD, VSS, dout);
  input clk;
  wire clk;
  input shift_in;
  wire shift_in;
  input data_in;
  wire data_in;
  input done_in;
  wire done_in;
  input reset;
  wire reset;
  input VDD;
  wire VDD;
  input VSS;
  wire VSS;
  output [11:0] dout;
  wire [11:0] dout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire \internal_data_reg[0] ;
  wire \internal_data_reg[10] ;
  wire \internal_data_reg[11] ;
  wire \internal_data_reg[1] ;
  wire \internal_data_reg[2] ;
  wire \internal_data_reg[3] ;
  wire \internal_data_reg[4] ;
  wire \internal_data_reg[5] ;
  wire \internal_data_reg[6] ;
  wire \internal_data_reg[7] ;
  wire \internal_data_reg[8] ;
  wire \internal_data_reg[9] ;
  sg13g2_inv_1 _049_ (
    .A(reset),
    .Y(_000_)
  );
  sg13g2_mux2_1 _050_ (
    .A0(dout[5]),
    .A1(\internal_data_reg[5] ),
    .S(done_in),
    .X(_047_)
  );
  sg13g2_mux2_1 _051_ (
    .A0(dout[4]),
    .A1(\internal_data_reg[4] ),
    .S(done_in),
    .X(_046_)
  );
  sg13g2_mux2_1 _052_ (
    .A0(dout[3]),
    .A1(\internal_data_reg[3] ),
    .S(done_in),
    .X(_045_)
  );
  sg13g2_mux2_1 _053_ (
    .A0(dout[2]),
    .A1(\internal_data_reg[2] ),
    .S(done_in),
    .X(_044_)
  );
  sg13g2_mux2_1 _054_ (
    .A0(dout[1]),
    .A1(\internal_data_reg[1] ),
    .S(done_in),
    .X(_043_)
  );
  sg13g2_mux2_1 _055_ (
    .A0(dout[0]),
    .A1(\internal_data_reg[0] ),
    .S(done_in),
    .X(_042_)
  );
  sg13g2_nor2b_1 _056_ (
    .A(done_in),
    .B_N(shift_in),
    .Y(_048_)
  );
  sg13g2_mux2_1 _057_ (
    .A0(\internal_data_reg[11] ),
    .A1(\internal_data_reg[10] ),
    .S(_048_),
    .X(_041_)
  );
  sg13g2_mux2_1 _058_ (
    .A0(\internal_data_reg[10] ),
    .A1(\internal_data_reg[9] ),
    .S(_048_),
    .X(_040_)
  );
  sg13g2_mux2_1 _059_ (
    .A0(\internal_data_reg[9] ),
    .A1(\internal_data_reg[8] ),
    .S(_048_),
    .X(_039_)
  );
  sg13g2_mux2_1 _060_ (
    .A0(\internal_data_reg[8] ),
    .A1(\internal_data_reg[7] ),
    .S(_048_),
    .X(_038_)
  );
  sg13g2_mux2_1 _061_ (
    .A0(\internal_data_reg[7] ),
    .A1(\internal_data_reg[6] ),
    .S(_048_),
    .X(_037_)
  );
  sg13g2_mux2_1 _062_ (
    .A0(\internal_data_reg[6] ),
    .A1(\internal_data_reg[5] ),
    .S(_048_),
    .X(_036_)
  );
  sg13g2_mux2_1 _063_ (
    .A0(\internal_data_reg[5] ),
    .A1(\internal_data_reg[4] ),
    .S(_048_),
    .X(_035_)
  );
  sg13g2_mux2_1 _064_ (
    .A0(\internal_data_reg[4] ),
    .A1(\internal_data_reg[3] ),
    .S(_048_),
    .X(_034_)
  );
  sg13g2_mux2_1 _065_ (
    .A0(\internal_data_reg[3] ),
    .A1(\internal_data_reg[2] ),
    .S(_048_),
    .X(_033_)
  );
  sg13g2_mux2_1 _066_ (
    .A0(\internal_data_reg[2] ),
    .A1(\internal_data_reg[1] ),
    .S(_048_),
    .X(_032_)
  );
  sg13g2_mux2_1 _067_ (
    .A0(\internal_data_reg[1] ),
    .A1(\internal_data_reg[0] ),
    .S(_048_),
    .X(_031_)
  );
  sg13g2_mux2_1 _068_ (
    .A0(\internal_data_reg[0] ),
    .A1(data_in),
    .S(_048_),
    .X(_030_)
  );
  sg13g2_mux2_1 _069_ (
    .A0(dout[11]),
    .A1(\internal_data_reg[11] ),
    .S(done_in),
    .X(_029_)
  );
  sg13g2_mux2_1 _070_ (
    .A0(dout[10]),
    .A1(\internal_data_reg[10] ),
    .S(done_in),
    .X(_028_)
  );
  sg13g2_mux2_1 _071_ (
    .A0(dout[9]),
    .A1(\internal_data_reg[9] ),
    .S(done_in),
    .X(_027_)
  );
  sg13g2_mux2_1 _072_ (
    .A0(dout[8]),
    .A1(\internal_data_reg[8] ),
    .S(done_in),
    .X(_026_)
  );
  sg13g2_mux2_1 _073_ (
    .A0(dout[7]),
    .A1(\internal_data_reg[7] ),
    .S(done_in),
    .X(_025_)
  );
  sg13g2_mux2_1 _074_ (
    .A0(dout[6]),
    .A1(\internal_data_reg[6] ),
    .S(done_in),
    .X(_024_)
  );
  sg13g2_inv_1 _075_ (
    .A(reset),
    .Y(_001_)
  );
  sg13g2_inv_1 _076_ (
    .A(reset),
    .Y(_002_)
  );
  sg13g2_inv_1 _077_ (
    .A(reset),
    .Y(_003_)
  );
  sg13g2_inv_1 _078_ (
    .A(reset),
    .Y(_004_)
  );
  sg13g2_inv_1 _079_ (
    .A(reset),
    .Y(_005_)
  );
  sg13g2_inv_1 _080_ (
    .A(reset),
    .Y(_006_)
  );
  sg13g2_inv_1 _081_ (
    .A(reset),
    .Y(_007_)
  );
  sg13g2_inv_1 _082_ (
    .A(reset),
    .Y(_008_)
  );
  sg13g2_inv_1 _083_ (
    .A(reset),
    .Y(_009_)
  );
  sg13g2_inv_1 _084_ (
    .A(reset),
    .Y(_010_)
  );
  sg13g2_inv_1 _085_ (
    .A(reset),
    .Y(_011_)
  );
  sg13g2_inv_1 _086_ (
    .A(reset),
    .Y(_012_)
  );
  sg13g2_inv_1 _087_ (
    .A(reset),
    .Y(_013_)
  );
  sg13g2_inv_1 _088_ (
    .A(reset),
    .Y(_014_)
  );
  sg13g2_inv_1 _089_ (
    .A(reset),
    .Y(_015_)
  );
  sg13g2_inv_1 _090_ (
    .A(reset),
    .Y(_016_)
  );
  sg13g2_inv_1 _091_ (
    .A(reset),
    .Y(_017_)
  );
  sg13g2_inv_1 _092_ (
    .A(reset),
    .Y(_018_)
  );
  sg13g2_inv_1 _093_ (
    .A(reset),
    .Y(_019_)
  );
  sg13g2_inv_1 _094_ (
    .A(reset),
    .Y(_020_)
  );
  sg13g2_inv_1 _095_ (
    .A(reset),
    .Y(_021_)
  );
  sg13g2_inv_1 _096_ (
    .A(reset),
    .Y(_022_)
  );
  sg13g2_inv_1 _097_ (
    .A(reset),
    .Y(_023_)
  );
  sg13g2_dfrbpq_1 _098_ (
    .CLK(clk),
    .D(_044_),
    .Q(dout[2]),
    .RESET_B(_020_)
  );
  sg13g2_dfrbpq_1 _099_ (
    .CLK(clk),
    .D(_045_),
    .Q(dout[3]),
    .RESET_B(_021_)
  );
  sg13g2_dfrbpq_1 _100_ (
    .CLK(clk),
    .D(_046_),
    .Q(dout[4]),
    .RESET_B(_022_)
  );
  sg13g2_dfrbpq_1 _101_ (
    .CLK(clk),
    .D(_047_),
    .Q(dout[5]),
    .RESET_B(_023_)
  );
  sg13g2_dfrbpq_1 _102_ (
    .CLK(clk),
    .D(_024_),
    .Q(dout[6]),
    .RESET_B(_000_)
  );
  sg13g2_dfrbpq_1 _103_ (
    .CLK(clk),
    .D(_025_),
    .Q(dout[7]),
    .RESET_B(_001_)
  );
  sg13g2_dfrbpq_1 _104_ (
    .CLK(clk),
    .D(_026_),
    .Q(dout[8]),
    .RESET_B(_002_)
  );
  sg13g2_dfrbpq_1 _105_ (
    .CLK(clk),
    .D(_027_),
    .Q(dout[9]),
    .RESET_B(_003_)
  );
  sg13g2_dfrbpq_1 _106_ (
    .CLK(clk),
    .D(_028_),
    .Q(dout[10]),
    .RESET_B(_004_)
  );
  sg13g2_dfrbpq_1 _107_ (
    .CLK(clk),
    .D(_029_),
    .Q(dout[11]),
    .RESET_B(_005_)
  );
  sg13g2_dfrbpq_1 _108_ (
    .CLK(clk),
    .D(_030_),
    .Q(\internal_data_reg[0] ),
    .RESET_B(_006_)
  );
  sg13g2_dfrbpq_1 _109_ (
    .CLK(clk),
    .D(_031_),
    .Q(\internal_data_reg[1] ),
    .RESET_B(_007_)
  );
  sg13g2_dfrbpq_1 _110_ (
    .CLK(clk),
    .D(_032_),
    .Q(\internal_data_reg[2] ),
    .RESET_B(_008_)
  );
  sg13g2_dfrbpq_1 _111_ (
    .CLK(clk),
    .D(_033_),
    .Q(\internal_data_reg[3] ),
    .RESET_B(_009_)
  );
  sg13g2_dfrbpq_1 _112_ (
    .CLK(clk),
    .D(_034_),
    .Q(\internal_data_reg[4] ),
    .RESET_B(_010_)
  );
  sg13g2_dfrbpq_1 _113_ (
    .CLK(clk),
    .D(_035_),
    .Q(\internal_data_reg[5] ),
    .RESET_B(_011_)
  );
  sg13g2_dfrbpq_1 _114_ (
    .CLK(clk),
    .D(_036_),
    .Q(\internal_data_reg[6] ),
    .RESET_B(_012_)
  );
  sg13g2_dfrbpq_1 _115_ (
    .CLK(clk),
    .D(_037_),
    .Q(\internal_data_reg[7] ),
    .RESET_B(_013_)
  );
  sg13g2_dfrbpq_1 _116_ (
    .CLK(clk),
    .D(_038_),
    .Q(\internal_data_reg[8] ),
    .RESET_B(_014_)
  );
  sg13g2_dfrbpq_1 _117_ (
    .CLK(clk),
    .D(_039_),
    .Q(\internal_data_reg[9] ),
    .RESET_B(_015_)
  );
  sg13g2_dfrbpq_1 _118_ (
    .CLK(clk),
    .D(_040_),
    .Q(\internal_data_reg[10] ),
    .RESET_B(_016_)
  );
  sg13g2_dfrbpq_1 _119_ (
    .CLK(clk),
    .D(_041_),
    .Q(\internal_data_reg[11] ),
    .RESET_B(_017_)
  );
  sg13g2_dfrbpq_1 _120_ (
    .CLK(clk),
    .D(_042_),
    .Q(dout[0]),
    .RESET_B(_018_)
  );
  sg13g2_dfrbpq_1 _121_ (
    .CLK(clk),
    .D(_043_),
    .Q(dout[1]),
    .RESET_B(_019_)
  );
endmodule
